server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: "/h2"

  datasource:
    url: jdbc:h2:mem:testdb
    username: "sa"
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  cache:
    type: none

  main:
    banner-mode: off